- server/db/models/index.js
- server/db/models/review.js
-Updated db/Model/index and db/Model/review
> Models-Index and Review

- package.json
- server/db/models/order.js
- server/db/models/orderItem.js
- server/db/models/product.js
created Order, OrderItem, Product models
> created Order, OrderItem, Product models

- server/db/models/index.js
- server/db/models/user.js
-is_admin 
- Address field
Did not need loggedIn field. Login Api handles this for us.
> User Model Changes

- client/components/all-products.js
- client/components/navbar.js
- client/components/product.js
- client/routes.js
- client/store/index.js
- client/store/products.js
- package-lock.json
- server/api/index.js
- server/api/products.js
added allproducts.js
added product.js 
added a redux file for allproducts
added a route file for allproducts
modified routes.js to make all products our homepage 
modified navbar to change from boilermaker to Covfefe
added route in index.js for routes as well
> allproducts basic done

- client/components/SingleProduct.js
- client/components/index.js
- client/components/navbar.js
- client/routes.js
- client/store/index.js
- client/store/singleProduct.js
- package-lock.json
- server/api/index.js
- server/api/products.js
Added Single Product front and back end; cleaned up merge conflicts of products and singleProduct
> Single product

- package-lock.json
- package.json
- public/index.html
npm i Bootstrap
added scripts to ./public/index.html
> installed Bootstrap and added scripts to index.html

- client/components/AddToCartButton.js
- client/components/SingleProduct.js
- client/store/cart.js
Cart Reducer and Button Component
> Cart Reducer and Button Component

- server/api/cart.js
- server/api/index.js
added route for cart and put it in index
> routes for cart

- client/components/Cart.jsx
- client/components/CartItem.jsx
- client/components/index.js
- client/routes.js
- client/store/index.js
- server/api/cart.js
> Cart & CartItem components and functionality

- server/api/cart.js
api/cart get/:userId res.json changed to type object {}
> api/cart get/:userId res.json changed to type object

- client/store/cart.js
fixed route and thunk when adding item to account for quantity
> fixed routes and thunk for quantity of adding a product

- client/components/AddToCartButton.jsx
- client/components/AllProducts.jsx
- client/components/Index.jsx
- client/components/Product.jsx
- client/components/SingleProductModal.jsx
- client/components/index.js
- client/routes.js
- client/store/cart.js
- client/store/index.js
- server/api/cart.js
> Removed SingleProductModal(Temp); add to cart button functioning

- client/components/Cart.jsx
- client/components/CartItem.jsx
- client/components/CheckOutButton.js
- client/components/RemoveButton.jsx
- client/components/index.js
- server/api/cart.js
> Checkout button

- client/components/AddToCartButton.jsx
- client/components/AllProducts.jsx
- client/components/Cart.jsx
- client/components/Product.jsx
- client/components/SingleProduct.jsx
- client/components/index.js
- client/routes.js
- server/api/cart.js
- server/api/products.js
ordered all requests. 
made button disabled if out of stock 
passed stock prop down to addItem button in single product and product components 
added ability to add the same item
> Fixing routes and button if out of stock

- client/components/AddToCartButton.jsx
- client/components/ProductAddedModal.jsx
- public/style.css
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_
> Modal Component Built

- client/components/Cart.jsx
- client/components/CheckOutButton.jsx
- client/components/RemoveButton.jsx
- client/store/cart.js
- package-lock.json
- package.json
- server/api/cart.js
- server/api/checkout.js
- server/api/index.js
- server/index.js
"User validation in carts, awaited destroy in carts, and added checkout routes and altered checkout button and what is being passed from cart to checkout button"
> Uservalidation

- client/components/AllProducts.jsx
- client/components/Product.jsx
- public/style.css
- server/api/middleware.js
- server/api/users.js
- server/db/models/user.js
> Admin middleware

- client/components/Cart.jsx
- client/components/SingleProduct.jsx
cart Total working and passed as prop to CheckOut component in Cart
> Cart Subtotal, Tax, Total are now functional

- client/components/AddToCartButton.jsx
- client/components/Product.jsx
- client/components/ProductAddedModal.jsx
- client/components/SingleProduct.jsx
- client/components/index.js
- public/style.css
> Modal Scroll

- client/components/AdminHome.jsx
- client/components/AdminUsers.jsx
- client/components/ProductAddedModal.jsx
- client/components/SingleProduct.jsx
- client/components/index.js
- client/routes.js
- client/store/index.js
- client/store/users.js
- server/api/cart.js
- server/api/middleware.js
- server/api/users.js
Added working Admin Home page: currently fetches all users. Minor tweaks to ProductAdded Modal. Moved NotFound route after the admin route. Added users reducer(might be able to put it back into user reducer but it was easier for me to do this way). Moved userCheck back to Cart back-end for now. I was having trouble using module.export for both middleware functions; for now just kept CheckAdmin in middleware file.
> Admin users

- client/components/Cart.jsx
- client/components/CartItem.jsx
- client/components/Quantity.jsx
- client/store/cart.js
- server/api/cart.js
> quantity change updates state and database => working!

- client/components/AdminEditProduct.jsx
- client/components/AdminHome.jsx
- client/components/AdminProducts.jsx
- client/components/CheckOutButton.jsx
- client/components/RemoveButton.jsx
- client/components/ReviewForm.jsx
- client/components/Reviews.jsx
- client/components/SingleReview.jsx
- client/routes.js
- client/store/products.js
- client/store/singleProduct.js
- server/api/checkout.js
- server/api/index.js
- server/api/products.js
- server/api/reviews.js
- Admin Products
-Edit products form
-backend routes
(you can access admin products by going to the /test route)
-Reviews renders each review. 
-leave a review form
> Admin products

- client/components/AddToCartButton.jsx
- client/components/AllProducts.jsx
- client/components/CartItem.jsx
- client/components/Product.jsx
- client/store/cart.js
- server/api/cart.js
> Styling tweaks

- client/components/Product.jsx
- client/components/Quantity.jsx
- public/style.css
- server/api/cart.js
add to cart if item not in cart issue resolved
> Add to cart fix

- client/components/AllProducts.jsx
- client/components/CheckOutButton.jsx
- client/components/Quantity.jsx
- client/components/SplashPage.jsx
- client/components/index.js
- client/routes.js
- client/store/index.js
- client/store/productFilter.js
- client/store/products.js
- server/api/cart.js
- server/api/checkout.js
- server/api/middleware.js
- server/api/products.js
checkout stock check, splash page with filtering, fixed carts
> checkout stock check, splash page with filtering, fixed carts
